### ISSUE TITLE
New Vision

### ISSUE THREAD

**Issue by Bl0u** [Bl0u/inventory-management-system#8]
# Todo list
- [ ] Build CRUD class that manipulates administrator DB
- [ ] Decide what the CRUD logic will be inside our main application
- [ ] Finish the CRUD logic in all the applications (admin, sup, cust, product, ...)
- [x] Finish log in project insights
